const fs=require('fs');const HTML=fs.readFileSync('index.html','utf8'),CSS=fs.readFileSync('static/app.css','utf8'),JS=fs.readFileSync('static/pro.js','utf8');
let p=0,f=0;const ok=(n,c)=>c?p++:(f++,console.log('  FAIL '+n));
console.log('[1] custom picker replaces native select');
ok('native template select is gone',!HTML.includes('id="rsBotTemplate"'));
ok('clear browse trigger exists',HTML.includes('id="rsBrowseTemplates"')&&HTML.includes('>Template<'));
ok('own code is explicit and template-free',HTML.includes('id="rsUseOwnCode"')&&HTML.includes('Full-screen editor')&&JS.includes('no template required'));
ok('code upload is a first-class source',HTML.includes('id="rsUploadCode"')&&/_setRunSpaceSourceMode\("upload"\)/.test(JS));
ok('picker is a real modal',HTML.includes('id="rsTemplateModal"')&&HTML.includes('id="rsTemplateGrid"'));
ok('search is available',HTML.includes('id="rsTemplateSearch"'));
ok('category rail is available',HTML.includes('id="rsTemplateCategories"'));
console.log('[2] useful card information');
ok('cards render name, description, framework and category',/t\.name/.test(JS)&&/t\.description/.test(JS)&&/t\.framework/.test(JS)&&/t\.category/.test(JS));
ok('picker filters by search',/toLowerCase\(\)\.includes\(search\)/.test(JS));
ok('picker filters by category',/_rsTemplateCategory==="All"\|\|t\.category===_rsTemplateCategory/.test(JS));
ok('selected template is reflected on trigger',/rsSelectedTemplate/.test(JS)&&/selected`/.test(JS));
ok('template strings use textContent, not card innerHTML',/card\.append\(top,desc,meta\)/.test(JS));
ok('templates can request optional setup values',/rsTemplateConfigFields/.test(HTML)&&/function _renderTemplateConfig/.test(JS));
console.log('[3] one-tap deploy after selection');
ok('tapping a template deploys instantly',/_applyRunSpaceBotTemplate[\s\S]*await _analyzeRunSpaceBot\(\)/.test(JS));
ok('double-tap is guarded while deploying',/_rsTemplateDeploying/.test(JS));
ok('required setup never blocks the run',/async function _analyzeRunSpaceBot[\s\S]*setupValues=_collectTemplateEnv\(false\)/.test(JS));
ok('setup values join the encrypted deployment env',/_collectTemplateEnv\(false\)/.test(JS)&&/BOT_TOKEN:_rsVerifiedBotToken/.test(JS));
ok('deploying state is visible on the button',/btn\.textContent="Deploying…"/.test(JS)&&/Deploying \$\{item\.name\}…/.test(JS));
ok('admin claim codes are generated automatically',/crypto\.getRandomValues/.test(JS)&&/field\.type==="generated"/.test(JS));
ok('claim code has a one-tap copy action',/copy\.textContent="Copy"/.test(JS)&&/navigator\.clipboard\.writeText/.test(JS));
ok('Go to bot deep link claims admin automatically',/start=claim_/.test(JS)&&/setupValues\.ADMIN_CLAIM_CODE/.test(JS));
ok('after-deploy instructions appear after success',/else if\(_rsTemplateAfterDeploy\)toast\("Deployed\. "/.test(JS));
ok('token verification detects name then opens source',/telegram_bot_username[\s\S]*_setBotWizardStage\("code"\)/.test(JS));
ok('source deploy is one click with spinner',/startJob\(\{launchAfterDeploy:true,launchUrl\}\)/.test(JS));
ok('template config box stays hidden in the wizard',/config\.hidden=true/.test(JS));
ok('gallery advertises complete products, not a padded count',/7 complete bot products/.test(HTML));
console.log('[4] responsive visual');
ok('desktop uses two-column cards',/\.rs-template-grid \{[^}]*grid-template-columns:1fr 1fr/.test(CSS));
ok('mobile uses one-column cards',/\.rs-template-grid\{grid-template-columns:1fr\}/.test(CSS));
ok('modal has one bounded scroll owner',/\.rs-template-modal-card \{[^}]*max-height:min\(86dvh,760px\); overflow-y:auto/.test(CSS));
ok('cards clear useful touch height',/\.rs-template-card \{[^}]*min-height:128px/.test(CSS));
console.log(`test_bot_template_picker: ${p} passed, ${f} failed`);process.exit(f?1:0);
