const fs=require('fs');const HTML=fs.readFileSync('index.html','utf8'),CSS=fs.readFileSync('static/app.css','utf8'),JS=fs.readFileSync('static/pro.js','utf8');
let p=0,f=0;const ok=(n,c)=>{c?p++:(f++,console.log('  FAIL '+n))};
console.log('[1] one action hierarchy');
ok('new bots hide duplicate menu Save',/_show\(btnRun, !!isSelected && !detailsPrimary\)/.test(JS)&&/if \(seg\) seg\.hidden = !isSelected/.test(JS));
ok('saved dirty bot says Save changes & run',/Save changes & run/.test(JS));
ok('stopped saved bot says Start bot',/Start bot/.test(JS));
ok('one user-facing details action',/id="btnFullDetails"/.test(HTML)&&/>Bot details</.test(HTML)&&/#tab-jobs #btnInspector \{ display:none !important/.test(CSS));
ok('close wording explains navigation',/>Back to bots</.test(HTML));
console.log('[2] product language and wizard');
ok('primary navigation says Bots',/(?:tab-tx|bn-l)">Bots</.test(HTML));
ok('wizard has exactly two steps',(HTML.match(/data-rs-step=/g)||[]).length===2);
ok('token is verified before choosing source',/data-rs-step="connect"><b>1<\/b> Connect bot/.test(HTML)&&/id="rsTgVerify"[^>]*>Verify bot</.test(HTML));
ok('mobile steps remain one row',/@media\(max-width:560px\)\{ \.rs-wizard-steps\{grid-template-columns:repeat\(2/.test(CSS));
ok('source action plainly says Deploy bot',/id="rsTgAnalyze"[^>]*>Deploy bot</.test(HTML)&&/Deploying…/.test(JS));
ok('custom code does not require a template',!/if\(!(?:select|_rsTemplate).*Choose a starter/.test(JS));
ok('only Source or Connect is shown',/function _setBotWizardStage/.test(JS)&&/connectStage\.hidden=!connect/.test(JS)&&!/reviewStage\.hidden/.test(JS));
ok('source can be changed without restarting',/id="rsChangeSource"/.test(HTML)&&/changeSource\.addEventListener/.test(JS));
ok('setup hides useless pre-deploy output',/body\.rs-composing\.rs-step-code #wbDivider,[^]{0,100}body\.rs-composing\.rs-step-code \.rs-logs \{ display:none/.test(CSS));
ok('one deploy click reaches the single-action launch page',/startJob\(\{launchAfterDeploy:true,launchUrl\}\)/.test(JS)&&/id="rsLaunchSuccess"/.test(HTML)&&/>Go to bot</.test(HTML));
console.log('[3] health is automatic but bounded');
ok('selected bot checks health automatically',/setTimeout\(\(\)=>_checkRunSpaceBotHealth\(\{id,silent:true\}\),250\)/.test(JS));
ok('health results are cached for 45 seconds',/Date\.now\(\)-cached\.at<45000/.test(JS));
ok('visible Bots tab refreshes at most once a minute',/setInterval\(\(\)=>\{if\(!document\.hidden&&_selectedJobId\).*\},60000\)/.test(JS));
ok('health copy avoids claiming normal operation',!/Running normally/.test(JS));
console.log(`test_runspace_design_cleanup: ${p} passed, ${f} failed`);process.exit(f?1:0);
