const fs=require('fs');
const CSS=fs.readFileSync('static/app.css','utf8');
const JS=fs.readFileSync('static/pro.js','utf8');
let pass=0,fail=0;const ok=(n,c,e)=>{if(c)pass++;else{fail++;console.log(`  FAIL ${n}${e?' -> '+e:''}`)}};
console.log('[1] composing state lifecycle');
ok('Add Bot enables the mobile composing layout',/document\.body\.classList\.add\("rs-composing"\)/.test(JS));
ok('opening a saved bot restores fixed IDE layout',/document\.body\.classList\.remove\("rs-composing","rs-step-code","rs-step-connect","rs-step-review","rs-own-code-editor"\)/.test(JS));
ok('successful deploy restores fixed IDE layout',/_composingNew = false;[^]{0,180}classList\.remove\("rs-composing","rs-step-code"/.test(JS));
console.log('[2] mobile flow fits instead of scrolling');
ok('Add Bot main pane does not become a long document',/body\.rs-composing #tab-jobs \.rs-main \{[^}]*overflow:hidden !important/.test(CSS));
ok('workspace is a bounded flex column',/body\.rs-composing #tab-jobs \.rs-ws \{[^}]*display:flex !important;[^}]*min-height:0;[^}]*overflow:hidden/.test(CSS));
ok('source editor uses only remaining space',/body\.rs-composing\.rs-step-code #tab-jobs \.rs-split \{[^}]*flex:1 1 auto;[^}]*height:auto;[^}]*min-height:180px/.test(CSS));
ok('pre-deploy output is hidden',/body\.rs-composing\.rs-step-code #tab-jobs \.rs-logs \{ display:none/.test(CSS));
ok('Connect removes editor entirely',/body\.rs-composing\.rs-step-connect #wbSplit[^]{0,100}display:none/.test(CSS));
ok('wizard has only two stages',/const order=\["connect","code"\]/.test(JS));
ok('divider cannot hijack mobile setup',/if \(_composingNew && window\.innerWidth <= 760\) return/.test(JS));
console.log('[3] launch page is intentionally single action');
ok('successful auto deploy enters launch page',/_showBotLaunchPage\(stub,options\.launchUrl/.test(JS));
ok('launch page hides app chrome',/body\.rs-launch-complete \.dash-bar,[^]{0,150}\.bottom-nav,[^]{0,150}\.rs-head \{ display:none !important/.test(CSS));
ok('launch page contains only Go to bot action',/\.rs-launch-success a \{/.test(CSS));
console.log(`test_runspace_touch_scroll: ${pass} passed, ${fail} failed`);process.exit(fail?1:0);
